name: build-joshua-base
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - /joshua-base/Containerfile
  pull_request:
    branches:
      - main
    paths:
      - /joshua-base/Containerfile

env:
  IMAGE_NAME: joshua-base
  REGISTRY: ghcr.io
  IMAGE_TAG: latest

jobs:
  build-and-push-joshua-base:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./${{ env.IMAGE_NAME }}/Containerfile            

      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Container Repository
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.REGISTRY }}/${{ github.actor }}

      - name: Set up Cosign
        uses: sigstore/cosign-installer@v3.5.0

      - name: Sign container images with a key
        uses: dodopizza/cosign-sign-push-action@0.0.7
        with:
          image-tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          image-digest: ${{ steps.push-to-ghcr.outputs.digest }}
          cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
          cosign-password: ${{ secrets.COSIGN_PASSWORD }}

      - name: Output image tags
        env:
          TAGS: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        run: |
          echo "## Built images with the following tags" >>$GITHUB_STEP_SUMMARY
          echo "${TAGS}" >>$GITHUB_STEP_SUMMARY
